INSERT INTO product_category(category_name) VALUES ('Books');
INSERT INTO product_category(category_name) VALUES ('Coffee Mugs');
INSERT INTO product_category(category_name) VALUES ('Mouse Pads');
INSERT INTO product_category(category_name) VALUES ('Luggage Tags');

-- BOOKS

INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Crash Course in Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1000.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Become a Guru in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1001.png', true, 100, 20.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring Vue.js', 'Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1002.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1003.png', true, 100, 13.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Crash Course in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1004.png', true, 100, 18.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'JavaScript Cookbook', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1005.png', true, 100, 23.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Beginners Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1006.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1007.png', true, 100, 16.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to Spring Boot', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1008.png', true, 100, 25.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Become a Guru in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1009.png', true, 100, 23.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Beginners Guide to Data Science', 'Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1010.png', true, 100, 24.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1011.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring DevOps', 'Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1012.png', true, 100, 24.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'The Expert Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1013.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1014.png', true, 100, 22.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('The Expert Guide to JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1015.png', true, 100, 22.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1016.png', true, 100, 27.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1017.png',true, 100, 13.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Introduction to C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1018.png', true, 100, 26.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Crash Course in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1019.png', true, 100, 13.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Introduction to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1020.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Become a Guru in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1021.png', true, 100, 18.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1022.png', true, 100, 26.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1023.png', true, 100, 22.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'The Expert Guide to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1024.png', true, 100, 16.99, 1);

-- -----------------------------------------------------
-- Coffee Mugs
-- -----------------------------------------------------
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Express', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1000.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Cherokee', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1001.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Sweeper', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1002.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Aspire', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1003.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Dorian', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1004.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Columbia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1005.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Worthing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1006.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Oak Cliff', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1007.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Tachyon', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1008.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug -Kyrgyz','Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1009.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Phase', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1010.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Falling', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1011.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Wispy', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1012.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Arlington', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1013.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Gazing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1014.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Azura', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1015.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Quantum Leap', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1016.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Light Years', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1017.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Taylor', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1018.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Gracia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1019.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Relax', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1020.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Windermere', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1021.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Prancer', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1022.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Recursion', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1023.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Treasure', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1024.png', true, 100, 18.99, 2);

-- Mouse Pads

INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Express', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1000.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Cherokee', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1001.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Sweeper', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1002.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Aspire', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1003.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Dorian', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1004.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Columbia', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1005.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Worthing', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1006.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Oak Cliff', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1007.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Tachyon', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1008.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Pan', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1009.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Phase', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1010.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Falling', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1011.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Wispy', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1012.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Arlington', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1013.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Gazing', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1014.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Azura', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1015.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Quantum Leap', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1016.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Light Years', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1017.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Taylor', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1018.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Gracia', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1019.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Relax', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1020.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Windermere', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1021.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Mouse Pad - Prancer', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1022.png', true, 100, 17.99, 3);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Recursion', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1023.png', true, 100, 17.99, 3);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Mouse Pad - Treasure', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1024.png', true, 100, 17.99, 3);


-- LUGGAGE TAGS

-- -----------------------------------------------------
-- Luggage Tags
-- -----------------------------------------------------
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Cherish', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1000.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Adventure', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1001.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Skyline', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1002.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Luggage Tag - River', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1003.png',  true, 100, 16.99, 4 );
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Trail Steps', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1004.png',  true, 100, 16.99, 4 );
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Blooming', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1005.png',  true, 100, 16.99, 4 );
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Park', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1006.png',  true, 100, 16.99, 4 );
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Beauty', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1007.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Water Fall', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1008.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Trail', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1009.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Skyscraper', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1010.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Luggage Tag - Leaf', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1011.png',  true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Jungle', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1012.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Shoreline', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1013.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Blossom', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1014.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Lock', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1015.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Cafe', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1016.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Darling', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1017.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Luggage Tag - Full Stack', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1018.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Courtyard', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1019.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Coaster', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1020.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Luggage Tag - Bridge', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1021.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Sunset', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1022.png', true, 100, 16.99, 4);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Flames', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1023.png', true, 100, 16.99, 4);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Luggage Tag - Countryside', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1024.png', true, 100, 16.99, 4);

