INSERT INTO product_category(category_name) VALUES ('Books');
INSERT INTO product_category(category_name) VALUES ('Coffee Mugs');
INSERT INTO product_category(category_name) VALUES ('Mouse Pads');
INSERT INTO product_category(category_name) VALUES ('Luggage Tags');

INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Crash Course in Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1000.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Become a Guru in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1001.png', true, 100, 20.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring Vue.js', 'Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1002.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1003.png', true, 100, 13.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Crash Course in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1004.png', true, 100, 18.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'JavaScript Cookbook', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1005.png', true, 100, 23.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Beginners Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1006.png', true, 100, 14.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1007.png', true, 100, 16.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to Spring Boot', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1008.png', true, 100, 25.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Become a Guru in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1009.png', true, 100, 23.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Beginners Guide to Data Science', 'Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1010.png', true, 100, 24.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1011.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring DevOps', 'Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1012.png', true, 100, 24.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'The Expert Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1013.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1014.png', true, 100, 22.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('The Expert Guide to JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1015.png', true, 100, 22.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Exploring React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1016.png', true, 100, 27.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1017.png',true, 100, 13.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Introduction to C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1018.png', true, 100, 26.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Crash Course in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1019.png', true, 100, 13.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Introduction to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1020.png', true, 100, 19.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Become a Guru in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1021.png', true, 100, 18.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Introduction to Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1022.png', true, 100, 26.99, 1);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Advanced Techniques in C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1023.png', true, 100, 22.99, 1);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'The Expert Guide to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1024.png', true, 100, 16.99, 1);

-- -----------------------------------------------------
-- Coffee Mugs
-- -----------------------------------------------------
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Express', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1000.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Cherokee', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1001.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Sweeper', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1002.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Aspire', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1003.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Dorian', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1004.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Columbia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1005.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Worthing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1006.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Oak Cliff', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1007.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Tachyon', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1008.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug -Kyrgyz','Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1009.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Phase', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1010.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Falling', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1011.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Wispy', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1012.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Arlington', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1013.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Gazing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1014.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Azura', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1015.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Quantum Leap', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1016.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Light Years', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1017.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Taylor', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1018.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Gracia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1019.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Relax', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1020.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ( 'Coffee Mug - Windermere', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1021.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Prancer', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1022.png', true, 100, 18.99, 2);
INSERT INTO products ( name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Recursion', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1023.png', true, 100, 18.99, 2);
INSERT INTO products (name, description, image_url, active, units_in_stock, unit_price, category_id) VALUES ('Coffee Mug - Treasure', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1024.png', true, 100, 18.99, 2);
